[2021-02-10 15:57:57,633]           base_events.py            ERROR:  Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main_loop() done, defined at /Users/ihorsemykopenko/Desktop/ITPEDIA/main.py:169> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiogram/utils/executor.py", line 312, in start_polling
    loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ihorsemykopenko/Desktop/ITPEDIA/main.py", line 173, in main_loop
  File "/Users/ihorsemykopenko/Desktop/ITPEDIA/parserFolder/parser.py", line 169, in comparison_index_in_file
    self.update_html()
  File "/Users/ihorsemykopenko/Desktop/ITPEDIA/parserFolder/parser.py", line 92, in update_html
    api = requests.get(self.url, config.headers)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 215, in resolve_redirects
    proxies = self.rebuild_proxies(prepared_request, proxies)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 292, in rebuild_proxies
    bypass_proxy = should_bypass_proxies(url, no_proxy=no_proxy)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/utils.py", line 760, in should_bypass_proxies
    bypass = proxy_bypass(parsed.hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 2643, in proxy_bypass
    return proxy_bypass_macosx_sysconf(host)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 2620, in proxy_bypass_macosx_sysconf
    return _proxy_bypass_macosx_sysconf(host, proxy_settings)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 2588, in _proxy_bypass_macosx_sysconf
    hostIP = socket.gethostbyname(hostonly)
KeyboardInterrupt
